spring:
  application:
    name: job-portal

management:
  tracing:
    service-name: job-portal
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
